"""Phase 2 Models and Phase 4/5 Updates

Revision ID: 8d6125830609
Revises: 7ddea97d9fc9
Create Date: 2026-07-02 23:21:39.752534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6125830609'
down_revision: Union[str, Sequence[str], None] = '7ddea97d9fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vip_list',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('identifier_type', sa.Enum('phone', 'email', name='identifiertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority_tag', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', 'identifier_type', name='uq_vip_identifier')
    )
    op.create_table('bank_accounts',
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('account_number')
    )
    op.create_table('beneficiaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('loan_type', sa.String(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('next_emi_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=False),
    sa.Column('merchant_category', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_number'], ['bank_accounts.account_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('card_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_number'], ['bank_accounts.account_number'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('current_workload', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('performance_score', sa.Numeric(precision=4, scale=2), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('admin', 'manager', 'support_agent', 'campaign_manager', 'compliance_officer', name='agentrole'),
               existing_nullable=False)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_account_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('suggested_reply', sa.String(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('open', 'waiting', 'awaiting_acc_no', 'resolved', 'closed', name='conversationstatus'),
               existing_nullable=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_tier', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('kyc_status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('primary_account_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('primary_account_number')
        batch_op.drop_column('kyc_status')
        batch_op.drop_column('customer_tier')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('open', 'waiting', 'awaiting_acc_no', 'resolved', 'closed', name='conversationstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.drop_column('suggested_reply')
        batch_op.drop_column('department')
        batch_op.drop_column('category')
        batch_op.drop_column('linked_account_number')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'manager', 'support_agent', 'campaign_manager', 'compliance_officer', name='agentrole'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('performance_score')
        batch_op.drop_column('is_available')
        batch_op.drop_column('current_workload')
        batch_op.drop_column('department')

    op.drop_table('cards')
    op.drop_table('account_transactions')
    op.drop_table('loans')
    op.drop_table('beneficiaries')
    op.drop_table('bank_accounts')
    op.drop_table('vip_list')
    # ### end Alembic commands ###
